language: python
sudo: false

python:
  - "2.7"

install:
  - mkdir lib
  - tar xf google.tgz -C lib
  - pip install -r requirements.txt --use-mirrors

script:
  - ./localization.sh
  - export PYTHONPATH=$PYTHONPATH:.:./lib
  - py.test app/tests --cov app --durations=10

after_success:
- coveralls
