application: better-translator
version: 4
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

handlers:
- url: /static
  static_dir: app/static
- url: .*
  script: run.app.app
